apiVersion: apps/v1
kind: Deployment
metadata:
  name: insta-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insta-app
  template:
    metadata:
      labels:
        app: insta-app
    spec:
      containers:
      - name: insta-app
        image: nginx:latest
        ports:
        - containerPort: 80

