events { }

http {
    server {
        listen 3000;

        # Frontend React App
        location / {
            proxy_pass http://host.docker.internal:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Auth Service
        location /auth/ {
            proxy_pass http://auth-service:3001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Media Service
        location /media/ {
            proxy_pass http://media-service:3002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Post Service
        location /posts/ {
            proxy_pass http://post-service:3003/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # User Service
        location /users/ {
            proxy_pass http://user-service:3004/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
